# Based off https://github.com/vegasbrianc/prometheus
version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  stastd:
    image: prom/statsd-exporter
    container_name: statsd
    expose:
      - 9125
      - 9102
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./config/prometheus/:/etc/prometheus/:Z"
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
